Removing suppressImplicitAnyIndexErrors from base/tsconfig.json
error TS5101: Option 'suppressImplicitAnyIndexErrors' is deprecated and will
stop functioning in TypeScript 5.5. Specify compilerOption
'"ignoreDeprecations": "5.0"' to silence this error.